// Tradiction 
function translate(){
    var intro = document.getElementById('intro');
    intro.innerText = "Vous réveillez-vous parfois groggy ? Se réveiller du mauvais côté du lit peut être moins lié à la quantité de sommeil que vous obtenez et plus à l'endroit où vous vous trouvez dans votre cycle de sommeil lorsque vous vous réveillez. Les humains connaissent plusieurs cycles pendant leur sommeil, et se réveiller au milieu du mauvais peut provoquer de la somnolence. Par conséquent, vous devez savoir de combien de repos vous avez besoin pour éviter de vous réveiller en cours de cycle, et la bonne nouvelle est que nous sommes là pour vous aider.Nous vous expliquerons comment utiliser notre calculateur de sommeil pour maximiser votre repos. De plus, nous verrons ce qui se passe pendant votre sommeil, pourquoi un repos de qualité est important, et plus encore.";
    var Stageosleep = document.getElementById('Stageosleep');
    Stageosleep.innerText = "Il existe quatre stades de sommeil [1], et ils sont divisés en deux phases, les mouvements oculaires rapides (REM) et les mouvements oculaires non rapides (non-REM). Les trois premières étapes impliquent le sommeil non-REM, tandis que la quatrième et dernière étape est le sommeil REM. Au cours d'un cycle, vous traverserez chacune de ces quatre étapes, en commençant par l'étape 1 du sommeil non REM et en terminant par REM. Par conséquent, pour terminer un cycle complet, vous devez terminer les quatre étapes. Une fois que vous avez terminé avec REM, vous passez ensuite à un autre cycle, en répétant ce schéma tout au long de la nuit. Chaque cycle dure environ 90 à 110 minutes.";
    var Remcyle = document.getElementById('Remcyle');
    Remcyle.innerText = "La dernière étape, REM, est lorsque vos ondes cérébrales recommencent à s'accélérer lorsque vous quittez un sommeil profond. Votre fréquence cardiaque et votre tension artérielle commencent également à augmenter et votre respiration devient plus rapide. Comme son nom l'indique, cette étape est également marquée par des mouvements oculaires plus rapides. REM, c'est aussi quand les gens rêvent habituellement. Cependant, pour éviter de réaliser physiquement ces rêves, vos jambes et vos bras restent dans un état de paralysie. Selon Valley Sleep Center [3], le REM est très important car il  stimule les zones de votre cerveau qui sont essentielles pour apprendre et créer ou conserver des souvenirs.  Au fur et à mesure que vous parcourez plusieurs étapes REM pendant la nuit, elles dureront d'abord environ 10 minutes, puis deviendront de plus en plus longues. La quantité de sommeil paradoxal dont vous avez besoin dépend de votre âge. Par exemple, ce sont les bébés et les jeunes enfants qui en ont le plus besoin, et cette quantité diminue à mesure que vous passez à l'adolescence et à l'âge adulte.";
    var Whatstage = document.getElementById('Whatstage');
    Whatstage.innerText = "L'étape 1 est un léger repos d'environ 5 à 10 minutes. Pendant ce temps, vos mouvements oculaires ralentissent et vos muscles commencent à se détendre. Vous pouvez également ressentir des secousses hypniques, une contraction musculaire soudaine. La deuxième étape est lorsque vos ondes cérébrales et votre rythme cardiaque ralentissent, que la température corporelle baisse et que les mouvements oculaires cessent. La deuxième étape dure généralement de 10 à 25 [2] minutes. Vous êtes dans un profond sommeil au cours de la troisième étape non REM et vous risquez de vous sentir désorienté si vous vous réveillez. De plus, vous générez des ondes cérébrales très lentes, c'est pourquoi cette étape est également connue sous le nom d'ondes lentes. Enfin, vous n'avez aucun mouvement oculaire ou musculaire.";
    var Theeffect = document.getElementById('Theeffect');
    Theeffect.innerText ="Les effets de la privation de sommeil sur votre corps Un repos insuffisant peut avoir un impact significatif sur votre bien-être. Non seulement cela peut nuire à votre santé physique, mais cela peut également affecter votre santé émotionnelle et cognitive. L'un des principaux effets d'un sommeil inadéquat est la fatigue diurne. De plus, se sentir trop fatigué pendant la journée augmente vos chances d'avoir un accident. Selon Johns Hopkins Medicine [4], 6 000 accidents de voiture mortels chaque année sont dus à la somnolence au volant. D'autres ramifications physiques comprennent un risque accru de maladie, de maladie cardiaque, d'hypertension artérielle, d'obésité, de cancer colorectal et de diabète de type 2. Un mauvais repos est également lié à une augmentation de la démence, des humeurs négatives et des difficultés de concentration.";
    var Howtosleep = document.getElementById('Howtosleep');
    Howtosleep.innerText ="Si vous sentez que votre sommeil est médiocre, vous pouvez faire des choses pour favoriser un meilleur repos. Le premier conseil est de maintenir une heure de coucher et de lever constante, y compris les week-ends. La bonne nouvelle est que vous pouvez utiliser la calculatrice pour vous aider à déterminer votre emploi du temps idéal, puis vous y tenir. Deuxièmement, évitez l'alcool, la caféine et la nicotine car ils peuvent perturber votre repos. De plus, se coucher rassasié ou affamé peut également affecter votre repos. Si vous faites des siestes, ne vous endormez pas trop tard dans la journée ou pendant plus de 30 minutes. L'activité physique devrait également vous aider à mieux vous reposer, alors pensez à aller courir ou marcher si vous avez besoin d'une recharge l'après-midi. Assurez-vous que votre chambre est propice à un repos de qualité en la gardant fraîche, calme et sombre. Enfin, aidez à réduire le stress qui peut vous empêcher de dormir en établissant une routine nocturne relaxante avant de vous coucher, comme lire un livre ou boire du thé chaud.";
    var Conclusion = document.getElementById('Conclusion');
    Conclusion.innerText ="Si vous souhaitez vous réveiller plus reposé, le calculateur de sommeil pourrait être la solution de vos rêves. Pendant que les gens se reposent, ils traversent quatre étapes. Les trois premiers sont non-REM et le quatrième est REM. Ensemble, ces quatre étapes forment un cycle complet. Le moment idéal pour se réveiller est pendant la première étape et la plus légère, et les experts suggèrent que les adultes obtiennent entre 5 et 6 cycles, ce qui équivaut à 7 à 9 heures de sommeil. Avec la calculatrice, vous pouvez mettre en place de bonnes habitudes pour améliorer encore votre sommeil. Votre médecin vous remerciera également de donner la priorité à votre sommeil car cela est essentiel pour garder votre santé sous contrôle.";
}
function translatee(){
    var intro = document.getElementById('intro');
    intro.innerText = "Do you sometimes wake up groggy? Waking up on the wrong side of the bed may be less about how much shuteye you get and more about where you are in your sleep cycle when you awaken. Humans experience multiple cycles while asleep, and waking in the middle of the wrong one could cause drowsiness.Therefore, you should know how much rest you need to avoid waking mid-cycle, and the good news is we are here to help.We'll walk you through how to use our sleep calculator to maximize your rest.Plus, we'll go over what happens while you sleep, why quality rest is important, and more.";
    var Stageosleep = document.getElementById('Stageosleep');
    Stageosleep.innerText = " There are four stages of sleep [1], and they are divided into two phases, rapid eye movement (REM) and non-rapid eye movement (non-REM). The first three stages involve non-REM sleep, while the fourth and final stage is REM sleep. During a cycle, you will move through each of these four stages, starting with Stage 1 of non-REM slumber and ending with REM. Therefore, to finish a full cycle, you need to complete all four stages. Once you are done with REM, you then move on to another cycle, repeating this pattern throughout the night. Each cycle lasts for about 90 to 110 minutes.";
    var Whatstage = document.getElementById('Whatstage');
    Whatstage.innerText = " Stage 1 is a light rest lasting roughly 5 to 10 minutes. During this time, your eye movement slows, and your muscles start relaxing. You may also experience hypnic jerking, a sudden muscle contraction. The second stage is when your brain waves and heart rate slow down, body temperature drops, and eye movement ceases. The second stage typically lasts 10 to 25 [2] minutes. You are in a deep slumber during the third non-REM stage, and you're likely to feel disoriented if awakened. Furthermore, you generate very slow brain waves, which is why this stage is also known as slow-wave. Lastly, you have no eye or muscle movement. ";
    var Remcyle = document.getElementById('Remcyle');
    Remcyle.innerText = " The final stage, REM, is when your brain waves begin to quicken again as you leave deep sleep. Your heart rate and blood pressure also start to rise, and your breathing becomes more rapid. As the name suggests, this stage is marked by faster eye movements as well. REM is also when people usually dream. To avoid physically acting out these dreams, though, your legs and arms remain in a state of paralysis. According to Valley Sleep Center [3], REM is highly important because it “stimulates the areas of your brain that are essential in learning and making or retaining memories. ” As you cycle through multiple REM stages during the night, they will first last around 10 minutes and then get increasingly longer. The amount of REM slumber you need depends on your age. For example, babies and young children need the most, and this amount decreases as you move into adolescence and adulthood. ";
    var Theeffect = document.getElementById('Theeffect');
    Theeffect.innerText ="Insufficient rest can have a significant impact on your well-being. Not only can it impair your physical health, but it can also affect your emotional and cognitive health. One of the primary effects of inadequate shuteye is daytime fatigue. Furthermore, feeling too tired during the day increases your chances of getting into an accident. According to Johns Hopkins Medicine [4], 6,000 fatal car crashes each year are due to drowsy driving. Other physical ramifications include an increased risk of illness, heart disease, high blood pressure, obesity, colorectal cancer, and type 2 diabetes. Poor rest is also linked to an increased of dementia, negative moods, and difficulty concentrating.";
    var Howtosleep = document.getElementById('Howtosleep');
    Howtosleep.innerText ="If you feel like your slumber is subpar, you can do things to promote better rest. The first tip is to maintain a consistent bedtime and wake-up time, including weekends. The great news is you can use the calculator to help determine your ideal schedule and then stick to that. Secondly, avoid alcohol, caffeine, and nicotine as they can disrupt your rest. Furthermore, going to bed full or hungry can also affect your rest. If you take naps, don't doze off too late in the day or for more than 30 minutes. Physical activity should also help you rest better, so consider going out for a run or walk if you need an afternoon recharge. Make sure your bedroom is conducive to quality rest by keeping it cool, quiet, and dark. Lastly, help alleviate stress that can keep you up by establishing a relaxing nightly routine before bed, such as reading a book or drinking hot tea.";
    var Conclusion = document.getElementById('Conclusion');
    Conclusion.innerText ="If you want to wake up more refreshed, the sleep calculator could be the solution of your dreams. While people rest, they move through four stages. The first three are non-REM, and the fourth is REM. Together, these four stages are a full cycle. The ideal time to wake up is during the first and lightest stage, and experts suggest adults get between 5 and 6 cycles, equating to 7 to 9 hours of shuteye. Along with the calculator, you can implement good habits to further improve your slumber. Your doctor will also thank you for prioritizing your sleep since this is vital to keeping your health in check.";


}
function translateee(){
    var intro = document.getElementById('intro');
    intro.innerText = "هل تستيقظ أحيانًا مترنحًا؟ قد يكون الاستيقاظ على الجانب الخطأ من السرير أقل في مقدار الراحة التي تحصل عليها والمزيد حول مكانك في دورة نومك عندما تستيقظ.يمر البشر بدورات متعددة أثناء النوم ، والاستيقاظ في منتصف دورة خاطئة يمكن أن يسبب النعاس.لذلك ، يجب أن تعرف مقدار الراحة التي تحتاجها لتجنب الاستيقاظ في منتصف الدورة ، والخبر السار هو أننا هنا للمساعدة.سنرشدك إلى كيفية استخدام حاسبة النوم الخاصة بنا لتحقيق أقصى قدر من الراحة.بالإضافة إلى ذلك ، سنستعرض ما يحدث أثناء النوم ، ولماذا تعتبر الراحة الجيدة أمرًا مهمًا ، وأكثر من ذلك.";
    var Whatstage = document.getElementById('Whatstage');
    Whatstage.innerText = "المرحلة الأولى هي راحة خفيفة تدوم من 5 إلى 10 دقائق تقريبًا. خلال هذا الوقت ، تتباطأ حركة عينيك ، وتبدأ عضلاتك في الاسترخاء. قد تعاني أيضًا من ارتعاش النوم ، وهو تقلص عضلي مفاجئ. المرحلة الثانية هي عندما تتباطأ موجات الدماغ ومعدل ضربات القلب ، وتنخفض درجة حرارة الجسم ، وتتوقف حركة العين. تدوم المرحلة الثانية عادةً من 10 إلى 25 [2] دقيقة. أنت في سبات عميق خلال المرحلة الثالثة من عدم حركة العين السريعة ، ومن المحتمل أن تشعر بالارتباك إذا استيقظت. علاوة على ذلك ، أنت تولد موجات دماغية بطيئة جدًا ، ولهذا تُعرف هذه المرحلة أيضًا باسم الموجة البطيئة. أخيرًا ، ليس لديك حركة عين أو عضلات.";
    var Remcyle = document.getElementById('Remcyle');
    Remcyle.innerText = "المرحلة الأخيرة ، REM ، هي عندما تبدأ موجات دماغك في التسارع مرة أخرى وأنت تغادر نومًا عميقًا. يبدأ معدل ضربات القلب وضغط الدم أيضًا في الارتفاع ، ويصبح تنفسك أسرع. كما يوحي الاسم ، تتميز هذه المرحلة بحركات عين أسرع أيضًا. حركة العين السريعة هي أيضًا عندما يحلم الناس عادةً. لتجنب تنفيذ هذه الأحلام جسديًا ، تظل ساقيك وذراعيك في حالة من الشلل. وفقًا لمركز  ، فإن حركة العين السريعة مهمة للغاية لأنها تحفز مناطق الدماغ الضرورية في التعلم وصنع الذكريات أو الاحتفاظ بها. أثناء قيامك بالدوران خلال مراحل حركة العين السريعة المتعددة أثناء الليل ، ستستمر أولًا حوالي 10 دقائق ثم تزداد مدة أطول. يعتمد مقدار نوم حركة العين السريعة الذي تحتاجه على عمرك. على سبيل المثال ، يحتاج الرضع والأطفال الصغار أكثر من غيرهم ، وتقل هذه الكمية كلما انتقلت إلى مرحلة المراهقة والبلوغ.";
    var Stageosleep = document.getElementById('Stageosleep');
    Stageosleep.innerText = "هناك أربع مراحل من النوم [1] ، وهي مقسمة إلى مرحلتين ، حركة العين السريعة (REM) وحركة العين غير السريعة (non-REM). تتضمن المراحل الثلاث الأولى نوم غير حركة العين السريعة ، بينما المرحلة الرابعة والأخيرة هي نوم الريم. خلال الدورة ، ستتحرك خلال كل مرحلة من هذه المراحل الأربع ، بدءًا من المرحلة 1 من نوم غير حركة العين السريعة وتنتهي بحركة العين السريعة. لذلك ، لإنهاء دورة كاملة ، تحتاج إلى إكمال جميع المراحل الأربع. بمجرد أن تنتهي من حركة العين السريعة ، تنتقل بعد ذلك إلى دورة أخرى ، وتكرر هذا النمط طوال الليل. تستمر كل دورة لمدة 90 إلى 110 دقيقة."

    var Theeffect = document.getElementById('Theeffect');
    Theeffect.innerText ="يمكن أن يكون للراحة غير الكافية تأثير كبير على صحتك. لا يمكن أن يضر بصحتك الجسدية فحسب ، بل يمكن أن يؤثر أيضًا على صحتك العاطفية والمعرفية. الإرهاق أثناء النهار هو أحد الآثار الأساسية لعدم كفاية النوم. علاوة على ذلك ، فإن الشعور بالتعب الشديد أثناء النهار يزيد من فرص وقوعك في حادث. وفقًا لجونز هوبكنز ميديسن [4] ، فإن 6000 حادث سيارة مميت كل عام بسبب النعاس. تشمل التداعيات الجسدية الأخرى زيادة خطر الإصابة بالأمراض وأمراض القلب وارتفاع ضغط الدم والسمنة وسرطان القولون والمستقيم وداء السكري من النوع 2. ترتبط قلة الراحة أيضًا بزيادة الخرف والحالات المزاجية السلبية وصعوبة التركيز.";
    var Howtosleep = document.getElementById('Howtosleep');
    Howtosleep.innerText ="كيفية تحسين جودة نومك إذا كنت تشعر أن نومك غير جيد ، يمكنك القيام بأشياء لتعزيز الراحة بشكل أفضل. النصيحة الأولى هي الحفاظ على وقت نوم واستيقاظ ثابت ، بما في ذلك عطلات نهاية الأسبوع. الخبر السار هو أنه يمكنك استخدام الآلة الحاسبة للمساعدة في تحديد جدولك الزمني المثالي ثم الالتزام بذلك. ثانيًا ، تجنب الكحول والكافيين والنيكوتين لأنها قد تعطل راحتك. علاوة على ذلك ، فإن الخلود إلى الفراش ممتلئًا أو جائعًا يمكن أن يؤثر أيضًا على راحتك. إذا كنت تأخذ قيلولة ، فلا تنام متأخرًا جدًا في اليوم أو لأكثر من 30 دقيقة. يجب أن يساعدك النشاط البدني أيضًا على الراحة بشكل أفضل ، لذا ضع في اعتبارك الخروج للركض أو المشي إذا كنت بحاجة إلى إعادة شحن طاقتك بعد الظهر. تأكد من أن غرفة نومك تساعد على الراحة الجيدة من خلال إبقائها باردة وهادئة ومظلمة. أخيرًا ، ساعد في تخفيف التوتر الذي يمكن أن يبقيك مستيقظًا عن طريق إنشاء روتين ليلي للاسترخاء قبل النوم ، مثل قراءة كتاب أو شرب الشاي الساخن.";
    var Conclusion = document.getElementById('Conclusion');
    Conclusion.innerText ="إذا كنت تريد الاستيقاظ أكثر انتعاشًا ، فقد تكون حاسبة النوم هي الحل الذي تحلم به. بينما يستريح الناس ، ينتقلون خلال أربع مراحل. الثلاثة الأولى هي غير حركة العين السريعة ، والرابعة هي حركة العين السريعة. معًا ، هذه المراحل الأربع عبارة عن دورة كاملة. الوقت المثالي للاستيقاظ هو خلال المرحلة الأولى والأخف ، ويقترح الخبراء أن يحصل البالغون على ما بين 5 و 6 دورات ، أي ما يعادل 7 إلى 9 ساعات من النوم. جنبًا إلى جنب مع الآلة الحاسبة ، يمكنك تنفيذ عادات جيدة لتحسين نومك بشكل أكبر. سيشكرك طبيبك أيضًا على إعطاء الأولوية لنومك لأن هذا أمر حيوي للحفاظ على صحتك تحت المراقبة.";

}
//Calcule Time sleep
var hours = document.getElementById("hour").value;
var minute = document.getElementById("minute").value;
var hoursx = 45;
var sleep = new URLSearchParams();
sleep.append("hours",hours);
sleep.append("min",minute);
console.log(minute);
document.getElementById('calculate').addEventListener('click', ()=>{
    location.href ="sleep3.html?"+ sleep.toString();
});